[[docs]]
  name = "Introduction"
  weight = 10
  identifier = "introduction"
  url = "/docs/introduction/"

[[docs]]
  name = "Getting Started"
  weight = 20
  identifier = "getting-started"
  url = "/docs/getting-started/"

[[docs]]
  name = "Eilmer"
  weight = 30
  identifier = "eilmer"
  url = "/docs/eilmer/"

[[docs]]
  name = "L1d"
  weight = 40
  identifier = "l1d"
  url = "/docs/l1d/"

[[docs]]
  name = "Pitot"
  weight = 50
  identifier = "pitot"
  url = "/docs/pitot/"

[[docs]]
  name = "ESTCN"
  weight = 60
  identifier = "estcn"
  url = "/docs/estcn/"

[[docs]]
  name = "NENZF1d"
  weight = 70
  identifier = "nenzf1d"
  url = "/docs/nenzf1d/"

[[docs]]
  name = "Python Libraries"
  weight = 80
  identifier = "python"
  url = "/docs/python"

[[docs]]
  name = "Grid Utilities"
  weight = 85
  identifier = "grid-utilities"
  url = "/docs/grid-utilities"

[[docs]]
  name = "Publications/Presentations"
  weight = 90
  identifier = "pub-n-pres"
  url = "/docs/pub-n-pres"

[[docs]]
  name = "All the Docs by Type"
  weight = 100
  identifier = "all-the-docs"
  url = "/docs/all-the-docs"

[[main]]
  name = "Docs"
  url = "/docs/introduction/about-the-toolkit/"
  weight = 10



[[social]]
name = "GitHub"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-github\"><path d=\"M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22\"></path></svg>"
  url = "https://github.com/gdtk-uq/gdtk"
  weight = 20


# [[footer]]
#   name = "Privacy"
#   url = "/privacy-policy/"
#   weight = 10
